apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: 759530261212.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-profile:1
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/profiledb"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
  - port: 3002
    targetPort: 3002
